name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: homebots/workflows/.github/workflows/docker-build-and-push.yml@master
    with:
      registry: ghcr.io
      org: ghcr.io/homebots
      imageName: debian-dev
      defaultBranch: main
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
